export const AttendancelogHistory = [
  {
    id: 1,
    tableHeading: "StaffID",
    tablesbody: [
      { tableData: "ESC001" },
      { tableData: "ESC003" },
      { tableData: "ESC045" },
      { tableData: "ESC089" },
      { tableData: "ESC005" },
      { tableData: "ESC101" },
      { tableData: "ESC100" },
      { tableData: "ESC046" },
      { tableData: "ESC050" },
      { tableData: "ESC050" },
    ],
  },
  {
    id: 2,
    tableHeading: "Fullname",
    tablesbody: [
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
      { tableData: "Austin Wisdom" },
    ],
  },
  {
    id: 3,
    tableHeading: "Date",
    tablesbody: [
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
    ],
  },
  {
    id: 4,
    tableHeading: "Time",
    tablesbody: [
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
      { tableDatabutton: "09:00 AM" },
    ],
  },
  {
    id: 5,
    tableHeading: "Log Type",
    tablesbody: [
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
      { tableDatabutton: "check in" },
    ],
  },
  {
    id: 6,
    tableHeading: "Action",
    tablesbody: [
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
    ],
  },
];
