export const StaffTableview = [
  {
    id: 1,
    tableHeading: "StaffID",
    tablesbody: [
      { tableData: "ESC001" },
      { tableData: "ESC003" },
      { tableData: "ESC045" },
      { tableData: "ESC089" },
      { tableData: "ESC005" },
      { tableData: "ESC101" },
      { tableData: "ESC100" },
      { tableData: "ESC046" },
      { tableData: "ESC050" },
      { tableData: "ESC050" },
    ],
  },
  {
    id: 2,
    tableHeading: "Firstname",
    tablesbody: [
      { tableData: "Austin" },
      { tableData: "Ejike" },
      { tableData: "Chris" },
      { tableData: "  Daniel" },
      { tableData: "Ibrahim" },
      { tableData: "Esther" },
      { tableData: "Chinaza" },
      { tableData: "Bola" },
      { tableData: "Rose" },
      { tableData: "Rose" },
    ],
  },
  {
    id: 3,
    tableHeading: "Lastname",
    tablesbody: [
      { tableData: "Godwin" },
      { tableData: "sunday" },
      { tableData: "Rock" },
      { tableData: "Avie" },
      { tableData: "Solomon" },
      { tableData: "Esther" },
      { tableData: "Chinaza" },
      { tableData: "Bola" },
      { tableData: "Godwin" },
      { tableData: "Rose" },
    ],
  },
  {
    id: 4,
    tableHeading: "Position",
    tablesbody: [
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Driver" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
      { tableDatabutton: "Teacher" },
    ],
  },
  {
    id: 5,
    tableHeading: "Department",
    tablesbody: [
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
      { tableDatabutton: "Academics" },
    ],
  },
  {
    id: 6,
    tableHeading: "Action",
    tablesbody: [
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
    ],
  },
];
