export const Tableview = [
  {
    id: 1,
    tableHeading: "Date",
    tablesbody: [
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
    ],
  },
  {
    id: 2,
    tableHeading: "Check in",
    tablesbody: [
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
    ],
  },
  {
    id: 3,
    tableHeading: "Check out",
    tablesbody: [
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
      { tableData: "April 03 2024" },
    ],
  },
  {
    id: 4,
    tableHeading: "Log Type",
    tablesbody: [
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
      { tableDatabutton: "check out" },
    ],
  },
  {
    id: 1,
    tableHeading: "Action",
    tablesbody: [
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
      { deleteIcon: true },
    ],
  },
];
